[graph]
all-features = false
no-default-features = false
exclude-unpublished = true

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
]
confidence-threshold = 0.9

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
